# Generated by Django 4.2.1 on 2023-06-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
