# Generated by Django 4.2.1 on 2023-06-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_verification_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderEmail', models.CharField(max_length=122)),
            ],
        ),
    ]
