# Generated by Django 4.2.1 on 2023-06-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_verifiedemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifiedEmail',
            new_name='Verification3',
        ),
    ]
