# Generated by Django 4.2.1 on 2023-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_verifiedemail_verification3'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification3',
            name='EmailDesc',
            field=models.CharField(default='N/A', max_length=122),
        ),
        migrations.AddField(
            model_name='verification3',
            name='SenderPassword',
            field=models.CharField(default='N/A', max_length=122),
        ),
        migrations.AddField(
            model_name='verification3',
            name='SenderSubject',
            field=models.CharField(default='N/A', max_length=122),
        ),
    ]
