# Generated by Django 4.2.1 on 2023-06-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_verification3_emaildesc_verification3_senderpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification3',
            name='SenderPassword',
        ),
    ]
