# Generated by Django 4.2.1 on 2023-06-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_verification3_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification3',
            name='files',
        ),
    ]
