# Generated by Django 4.2.1 on 2023-06-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_filesupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
