# Generated by Django 4.2.1 on 2023-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_filesupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='verification',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='verification3',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
